// generated by mBlock5 for mBot
// codes make you happy

#include <MeMCore.h>
#include <Arduino.h>
#include <Wire.h>
#include <SoftwareSerial.h>

MeBuzzer buzzer;
int durchgaenge = 0;

void setup() {
  Serial.begin(9600);

}


void loop() {
  durchgaenge++;
  Serial.println(durchgaenge);

  if(durchgaenge < 4)
{
    buzzer.tone(262, 0.25 * 1000);
    delay(20);
    buzzer.tone(700, 1 * 1000);
  }
}
